---
title: "Liesl Mary Final"
output: flexdashboard::flex_dashboard
runtime: shiny
---
About
==========================


```{r libraries and data, include = FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(lubridate)
library(stringr)
library(emojifont)
library(ggtext)
library(leaflet)
library(sf)
library(tidyverse)
library(readr)
library(jsonlite)
library(wordcloud)
library(tidytext)
data("rats_location")
data("rats_graph")
data("airbnb_parsed")

```


```{r data entry, include=FALSE}
airbnb_data <- read_csv("airbnb_data.csv")

rats <- read_csv("Rat_Sightings_20240507.csv")|>
  filter(Latitude!="NA",
         Longitude!="NA")

parks <- read_csv("Parks_Properties_20240507.csv")
parks_sf <- st_as_sf(parks, wkt = "multipolygon")


url<- "https://data.cityofnewyork.us/resource/fi97-k4k6.json"

farmers_markets <- fromJSON(url)|>
  mutate(latitude=as.numeric(latitude),
         longitude=as.numeric(longitude))



manhattan_lat_range <- c(40.70, 40.88)
manhattan_lon_range <- c(-74.02, -73.93)

brooklyn_lat_range <- c(40.57, 40.74)
brooklyn_lon_range <- c(-74.04, -73.82)

queens_lat_range <- c(40.53, 40.79)
queens_lon_range <- c(-73.96, -73.71)

bronx_lat_range <- c(40.79, 40.92)
bronx_lon_range <- c(-73.93, -73.73)

staten_island_lat_range <- c(40.48, 40.65)
staten_island_lon_range <- c(-74.27, -74.04)


airbnb_with_boroughs<-airbnb_data|>
  mutate(borough = ifelse(airbnb_data$Latitude >= manhattan_lat_range[1] & airbnb_data$Latitude <= manhattan_lat_range[2] &
                                airbnb_data$Longitude >= manhattan_lon_range[1] & airbnb_data$Longitude <= manhattan_lon_range[2],
                              "Manhattan",
                              ifelse(airbnb_data$Latitude >= brooklyn_lat_range[1] & airbnb_data$Latitude <= brooklyn_lat_range[2] &
                                       airbnb_data$Longitude >= brooklyn_lon_range[1] & airbnb_data$Longitude <= brooklyn_lon_range[2],
                                     "Brooklyn",
                                     ifelse(airbnb_data$Latitude >= queens_lat_range[1] & airbnb_data$Latitude <= queens_lat_range[2] &
                                              airbnb_data$Longitude >= queens_lon_range[1] & airbnb_data$Longitude <= queens_lon_range[2],
                                            "Queens",
                                            ifelse(airbnb_data$Latitude >= bronx_lat_range[1] & airbnb_data$Latitude <= bronx_lat_range[2] &
                                                     airbnb_data$Longitude >= bronx_lon_range[1] & airbnb_data$Longitude <= bronx_lon_range[2],
                                                   "Bronx",
                                                   ifelse(airbnb_data$Latitude >= staten_island_lat_range[1] & airbnb_data$Latitude <= staten_island_lat_range[2] &
                                                            airbnb_data$Longitude >= staten_island_lon_range[1] & airbnb_data$Longitude <= staten_island_lon_range[2],
                                                      "Staten Island", "No Borough"))))))

airbnb_data <- read_csv("airbnb_data.csv")

rats <- read_csv("Rat_Sightings_20240507.csv")|>
  filter(Latitude!="NA",
         Longitude!="NA")

parks <- read_csv("Parks_Properties_20240507.csv")
parks_sf <- st_as_sf(parks, wkt = "multipolygon")


url<- "https://data.cityofnewyork.us/resource/fi97-k4k6.json"

farmers_markets <- fromJSON(url)|>
  mutate(latitude=as.numeric(latitude),
         longitude=as.numeric(longitude))

rats_graph<-rats|>
  sample_n(225)  |>
  select(Latitude, Longitude) 


airbnb_parsed <- airbnb_data |>
  select(Name, Title, Id, `Listing URL`, Price, Beds, Baths, Bedrooms, `Average Rating`, `Number of Reviews`, `More Details`, `Listing Type`, `Room Type Category`) |>
  mutate(price_parsed = parse_number(Price))
```


```{r}
leaflet() |>
    addTiles() |>
    setView(lng = mean(airbnb_data$Longitude), lat = mean(airbnb_data$Latitude), 
            zoom = 10) |> 
    addCircleMarkers(data = airbnb_data,
        lat = ~ Latitude, 
        lng = ~ Longitude, 
        popup = ~ Name, 
        radius = ~ 10,  
        weight = 3,
        color = "hotpink", 
        fillColor = "pink")
```

Airbnb with Other Variable
==========================
```{r interactive map, echo = FALSE}
house_icon <- makeIcon(
  iconUrl = "https://www.iconeasy.com/icon/png/System/Vista%20General/house.png",
  iconWidth = 29,
  iconHeight = 29
)

rat_icon <- makeIcon(
  iconUrl = "https://icons.iconarchive.com/icons/google/noto-emoji-animals-nature/256/22251-rat-icon.png",
  iconWidth = 28,
  iconHeight = 28
)

leaflet() |>
  addTiles() |>
  setView(lng = -74.00, lat = 40.71, zoom = 12) |>
  addMarkers(data = airbnb_data, lng = ~Longitude, lat = ~Latitude, icon = house_icon,
     popup = ~paste("<a href='", `Listing URL`, "'><b>", Title, "</b></a>", "</br>", Name, "</br>", Price, Qualifier))|>
  addMarkers(data=rats_graph, lng=~Longitude, lat=~Latitude, icon = rat_icon, popup = ~paste("squeak squeak:)"))

```

```{r}
carrot_icon <- makeIcon(
  iconUrl = "https://images.emojiterra.com/google/noto-emoji/unicode-15.1/color/svg/1f955.svg",
  iconWidth = 29,
  iconHeight = 29
)

leaflet() |>
  addTiles() |>
  setView(lng = -74.00, lat = 40.71, zoom = 12)|>
  addMarkers(data=farmers_markets, lng=~longitude, lat=~latitude, icon = carrot_icon, popup = ~paste(marketname, "</br>", daysoperation, hoursoperations))
```

```{r}
leaflet() |>
  addTiles() |>
  setView(lng = -74.00, lat = 40.71, zoom = 12)|>
  addPolygons(data=parks_sf, color="deeppink", popup = ~paste(SIGNNAME))
```

Description Word Analysis
==========================
```{r}
word <- airbnb_data |>
  select(Name) |>
  mutate(Name = str_to_lower(Name),
         word = str_split(Name, "\\s+"))|>
         unnest(word) |>
  mutate(word = str_remove_all(word, "[^[:alpha:]]")) |>
  anti_join(stop_words) |>
  count(word, sort=TRUE)|>
  slice(2:378)

pinkalicious <- c("#FF6FFF", "#FF5D99", "hotpink", "#FFCFF7", "deeppink")


wordcloud(words = word$word, freq = word$n, min.freq = 1,
          max.words = 100, random.order = FALSE, rot.per = 0.35, 
          colors = pinkalicious)

```

Summary Statistics By Borough
==========================
```{r}
airbnb_with_boroughs|>
  mutate(Price=parse_number(Price))|>
  group_by(borough)|>
  ggplot()+
  geom_boxplot(aes(y = borough, x = Price), color="deeppink") +
  theme_minimal() +
  labs(y = "Borough", x = "Price") 
#Replace Price with "Beds", "Baths", `Average Rating`,`Number of Reviews`, `Cleanliness Rating`, etc.
#Note that Staten Island only has one listing
```


Two Variable Comparison
==========================
```{r}
airbnb_parsed |>
  ggplot(aes(y = price_parsed, x = `Average Rating`)) +
  geom_point() 
```

Our Favorites
==========================



Conclusion
==========================


