---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(tidyr)
library(lubridate)
library(stringr)
library(emojifont)
library(ggtext)
library(leaflet)
library(sf)
library(readr)
library(jsonlite)
library(wordcloud)
library(tidytext)
```

```{r, include=FALSE}
airbnb_data <- read_csv("airbnb_data.csv")

rats <- read_csv("Rat_Sightings_20240507.csv")|>
  filter(Latitude!="NA",
         Longitude!="NA")

parks <- read_csv("Parks_Properties_20240507.csv")
parks_sf <- st_as_sf(parks, wkt = "multipolygon")


url<- "https://data.cityofnewyork.us/resource/fi97-k4k6.json"

farmers_markets <- fromJSON(url)|>
  mutate(latitude=as.numeric(latitude),
         longitude=as.numeric(longitude))
```

```{r, include=FALSE}
rats_location <- rats |>
  select(Latitude, Longitude) 

rats_graph<-rats_location|>
  sample_n(225)  

```

```{r, include=FALSE}
airbnb_location<-airbnb_data|>
  select(Latitude, Longitude)
```

##Two variable comparisons data
```{r}
airbnb_parsed <- airbnb_data |>
  select(Name, Title, Id, `Listing URL`, Price, Beds, Baths, Bedrooms, `Average Rating`, `Number of Reviews`, `More Details`, `Listing Type`, `Room Type Category`) |>
  mutate(price_parsed = parse_number(Price))
```

##Boroughs
```{r}
manhattan_lat_range <- c(40.70, 40.88)
manhattan_lon_range <- c(-74.02, -73.93)

brooklyn_lat_range <- c(40.57, 40.74)
brooklyn_lon_range <- c(-74.04, -73.82)

queens_lat_range <- c(40.53, 40.79)
queens_lon_range <- c(-73.96, -73.71)

bronx_lat_range <- c(40.79, 40.92)
bronx_lon_range <- c(-73.93, -73.73)

staten_island_lat_range <- c(40.48, 40.65)
staten_island_lon_range <- c(-74.27, -74.04)


airbnb_with_boroughs<-airbnb_data|>
  mutate(borough = ifelse(airbnb_data$Latitude >= manhattan_lat_range[1] & airbnb_data$Latitude <= manhattan_lat_range[2] &
                                airbnb_data$Longitude >= manhattan_lon_range[1] & airbnb_data$Longitude <= manhattan_lon_range[2],
                              "Manhattan",
                              ifelse(airbnb_data$Latitude >= brooklyn_lat_range[1] & airbnb_data$Latitude <= brooklyn_lat_range[2] &
                                       airbnb_data$Longitude >= brooklyn_lon_range[1] & airbnb_data$Longitude <= brooklyn_lon_range[2],
                                     "Brooklyn",
                                     ifelse(airbnb_data$Latitude >= queens_lat_range[1] & airbnb_data$Latitude <= queens_lat_range[2] &
                                              airbnb_data$Longitude >= queens_lon_range[1] & airbnb_data$Longitude <= queens_lon_range[2],
                                            "Queens",
                                            ifelse(airbnb_data$Latitude >= bronx_lat_range[1] & airbnb_data$Latitude <= bronx_lat_range[2] &
                                                     airbnb_data$Longitude >= bronx_lon_range[1] & airbnb_data$Longitude <= bronx_lon_range[2],
                                                   "Bronx",
                                                   ifelse(airbnb_data$Latitude >= staten_island_lat_range[1] & airbnb_data$Latitude <= staten_island_lat_range[2] &
                                                            airbnb_data$Longitude >= staten_island_lon_range[1] & airbnb_data$Longitude <= staten_island_lon_range[2],
                                                      "Staten Island", "No Borough"))))))


```